WINDUPRULE-723 Quarkus Release 1.12 - run.jar issue
windup/windup-rulesets pull request #536
Opened 2021-03-01 11:08 UTC by PhilipCattanach

2021-03-01 11:09 UTC, PhilipCattanach commented
@m-brophy this is very similar to WINDUPRULE-715 using the same criteria. Just a different issue and link generated. Thanks.

2021-03-03 09:41 UTC, m-brophy requested changes

2021-03-03 09:41 UTC, m-brophy commented on rules-reviewed/quarkus1/quarkus1-11/quarkus1-12-run-jar.windup.xml
> +            This ruleset gives hints for upgrading to Quarkus 1.12 - Fast-jar as default
description refers to fast-jar

2021-03-03 09:41 UTC, m-brophy commented on rules-reviewed/quarkus1/quarkus1-11/quarkus1-12-run-jar.windup.xml
> +                <hint title="Starting the application with the -run.jar" effort="1" category-id="potential">
stray hyphen in the title

2021-03-03 09:41 UTC, m-brophy commented on rules-reviewed/quarkus1/quarkus1-11/tests/quarkus1-12-run-jar.windup.test.xml
> +                    <fail message="[quarkus1-12-run-jar-00000] The fast-jar hint was not found!" />
fail message refers to fast-jar

2021-03-03 14:26 UTC, m-brophy approved these changes

2021-03-03 14:27 UTC, merged